const MYSQL_USERS_TABLE = `CREATE TABLE IF NOT EXISTS users(
    id INTEGER NOT NULL AUTO_INCREMENT, 
    name TEXT NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    avatar TEXT ,
    address VARCHAR(50),
    status VARCHAR(50),
    active CHAR(1),
    PRIMARY KEY(id),
    UNIQUE(email, username))`;

const MYSQL_QUESTIONS_TABLE = `CREATE TABLE IF NOT EXISTS questions(
    id INTEGER NOT NULL AUTO_INCREMENT,
    title VARCHAR(50),
    toUser INTEGER,
    fromUser INTEGER,
    askedDate VARCHAR(50),
    PRIMARY KEY(id),
    FOREIGN KEY(toUser) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(fromUser) REFERENCES users(id) ON DELETE CASCADE)`;

const MYSQL_FOLLOWS_TABLE = `CREATE TABLE IF NOT EXISTS follows(
    id INTEGER NOT NULL AUTO_INCREMENT,
    fromUser INTEGER,
    toUser INTEGER,
    PRIMARY KEY(id),
    UNIQUE(fromUser,toUser),
    FOREIGN KEY(toUser) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(fromUser) REFERENCES users(id) ON DELETE CASCADE)`;


exports.MYSQL_USERS_TABLE = MYSQL_USERS_TABLE;

exports.MYSQL_QUESTIONS_TABLE = MYSQL_QUESTIONS_TABLE;

exports.MYSQL_FOLLOWS_TABLE = MYSQL_FOLLOWS_TABLE;